name: cd

on:
  push:
    branches: [main]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  mint-token:
    if: "${{ github.ref_type == 'branch' && !startsWith(github.event.head_commit.message, 'chore: release') }}"
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.app-token.outputs.token }}
    steps:
      - name: Mint GitHub app token
        id: app-token
        uses: actions/create-github-app-token@v3.2.0
        with:
          client-id: ${{ vars.OCTO_BUDDY_CLIENT_ID }}
          private-key: ${{ secrets.OCTO_BUDDY_PRIVATE_KEY }}
          repositories: ${{ github.event.repository.name }}
          permission-contents: write
          permission-issues: write
          permission-pull-requests: write

  release:
    needs: mint-token
    if: "${{ github.ref_type == 'branch' && !startsWith(github.event.head_commit.message, 'chore: release') }}"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: nickdemianchuk/actions/.github/workflows/release.yml@main
    secrets:
      GH_TOKEN: ${{ needs.mint-token.outputs.token }}

  tf-apply:
    if: github.ref_type == 'tag' || github.event_name == 'workflow_dispatch'
    uses: nickdemianchuk/actions/.github/workflows/tf-apply.yml@main
    permissions:
      contents: read
      pull-requests: write
    with:
      workspace: ${{ github.event.repository.name }}
    secrets:
      TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
